2022-06-21 19:47:23,087 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-21 19:47:23,090 INFO supervisord started with pid 8
2022-06-21 19:47:24,099 INFO spawned: 'nginx' with pid 11
2022-06-21 19:47:24,106 INFO spawned: 'app' with pid 12
Bottle v0.12.21 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

2022-06-21 19:47:25,982 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-21 19:47:25,982 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 21.06.22 19:47:27] [Level: info] id: 100444d9760f5d1a
[Time: 21.06.22 19:47:27] [Level: info] coordinator: False
[Time: 21.06.22 19:47:27] [Level: info] clients: ['7b839daa2789500a', '100444d9760f5d1a']
[Time: 21.06.22 19:47:27] [Level: info] state: initial
[Time: 21.06.22 19:47:27] [Level: info] transition: read
127.0.0.1 - - [21/Jun/2022 19:47:27] "POST /api/setup HTTP/1.0" 200 0
[CTRL] GET /status
127.0.0.1 - - [21/Jun/2022 19:47:27] "GET /api/status HTTP/1.0" 200 126
[Time: 21.06.22 19:47:28] [Level: info] state: read
[Time: 21.06.22 19:47:28] [Level: info] transition: await
[Time: 21.06.22 19:47:29] [Level: info] state: await
[CTRL] GET /status
127.0.0.1 - - [21/Jun/2022 19:47:30] "GET /api/status HTTP/1.0" 200 126
[CTRL] GET /data
127.0.0.1 - - [21/Jun/2022 19:47:30] "GET /api/data HTTP/1.0" 200 18166
[CTRL] POST /data
127.0.0.1 - - [21/Jun/2022 19:47:31] "POST /api/data?client=7b839daa2789500a HTTP/1.0" 200 0
[Time: 21.06.22 19:47:31] [Level: info] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 169, in guarded_run
    self.run()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 184, in run
    transition = self.current_state.run()
  File "/app/states.py", line 84, in run
    c.delete_columns(to_drop)
  File "/app/states.py", line 24, in delete_columns
    self.df = self.df.drop(columns=to_drop)
  File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 4954, in drop
    return super().drop(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 4267, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 4311, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6640, in drop
    indexer = self.get_indexer_for(labels)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5764, in get_indexer_for
    return self.get_indexer(target)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3784, in get_indexer
    return self._get_indexer(target, method, limit, tolerance)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3809, in _get_indexer
    indexer = self._engine.get_indexer(tgt_values)
  File "pandas/_libs/index.pyx", line 305, in pandas._libs.index.IndexEngine.get_indexer
  File "pandas/_libs/hashtable_class_helper.pxi", line 5247, in pandas._libs.hashtable.PyObjectHashTable.lookup
TypeError: unhashable type: 'Index'

[CTRL] GET /status
127.0.0.1 - - [21/Jun/2022 19:47:33] "GET /api/status HTTP/1.0" 200 133
