2022-06-22 07:52:42,680 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-22 07:52:42,685 INFO supervisord started with pid 9
2022-06-22 07:52:43,688 INFO spawned: 'nginx' with pid 12
2022-06-22 07:52:43,693 INFO spawned: 'app' with pid 13
Bottle v0.12.21 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

2022-06-22 07:52:45,672 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-22 07:52:45,672 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 22.06.22 07:52:46] [Level: info] id: f4bd841383333b67
[Time: 22.06.22 07:52:46] [Level: info] coordinator: False
[Time: 22.06.22 07:52:46] [Level: info] clients: ['f4bd841383333b67', 'fb762f7e3b456c9f']
[Time: 22.06.22 07:52:46] [Level: info] state: initial
[Time: 22.06.22 07:52:46] [Level: info] transition: read
[CTRL] GET /status
127.0.0.1 - - [22/Jun/2022 07:52:46] "POST /api/setup HTTP/1.0" 200 0
127.0.0.1 - - [22/Jun/2022 07:52:46] "GET /api/status HTTP/1.0" 200 126
[Time: 22.06.22 07:52:47] [Level: info] state: read
[Time: 22.06.22 07:52:47] [Level: info] transition: await
[Time: 22.06.22 07:52:48] [Level: info] state: await
[CTRL] GET /status
127.0.0.1 - - [22/Jun/2022 07:52:49] "GET /api/status HTTP/1.0" 200 126
[CTRL] GET /data
127.0.0.1 - - [22/Jun/2022 07:52:49] "GET /api/data HTTP/1.0" 200 18166
[CTRL] POST /data
127.0.0.1 - - [22/Jun/2022 07:52:50] "POST /api/data?client=fb762f7e3b456c9f HTTP/1.0" 200 0
[Time: 22.06.22 07:52:50] [Level: info] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 169, in guarded_run
    self.run()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 184, in run
    transition = self.current_state.run()
  File "/app/states.py", line 85, in run
    c.delete_columns(to_drop=to_drop)
  File "/app/states.py", line 23, in delete_columns
    self.df = self.df.drop(columns=to_drop)
  File "/usr/local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 4954, in drop
    return super().drop(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 4267, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 4311, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 6640, in drop
    indexer = self.get_indexer_for(labels)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5764, in get_indexer_for
    return self.get_indexer(target)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3784, in get_indexer
    return self._get_indexer(target, method, limit, tolerance)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3809, in _get_indexer
    indexer = self._engine.get_indexer(tgt_values)
  File "pandas/_libs/index.pyx", line 305, in pandas._libs.index.IndexEngine.get_indexer
  File "pandas/_libs/hashtable_class_helper.pxi", line 5247, in pandas._libs.hashtable.PyObjectHashTable.lookup
TypeError: unhashable type: 'Index'

[CTRL] GET /status
127.0.0.1 - - [22/Jun/2022 07:52:52] "GET /api/status HTTP/1.0" 200 133
