2022-06-21 20:03:25,873 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-21 20:03:25,875 INFO supervisord started with pid 9
2022-06-21 20:03:26,884 INFO spawned: 'nginx' with pid 12
2022-06-21 20:03:26,898 INFO spawned: 'app' with pid 13
Bottle v0.12.21 server starting up (using WSGIRefServer())...
Listening on http://localhost:5000/
Hit Ctrl-C to quit.

2022-06-21 20:03:28,732 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-06-21 20:03:28,733 INFO success: app entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[CTRL] POST /setup
[Time: 21.06.22 20:03:29] [Level: info] id: dad6dae50cb8d66a
[Time: 21.06.22 20:03:29] [Level: info] coordinator: False
[Time: 21.06.22 20:03:29] [Level: info] clients: ['a1412abbd77cf888', 'dad6dae50cb8d66a']
[Time: 21.06.22 20:03:29] [Level: info] state: initial
[Time: 21.06.22 20:03:29] [Level: info] transition: read
127.0.0.1 - - [21/Jun/2022 20:03:29] "POST /api/setup HTTP/1.0" 200 0
[CTRL] GET /status
127.0.0.1 - - [21/Jun/2022 20:03:29] "GET /api/status HTTP/1.0" 200 126
[Time: 21.06.22 20:03:30] [Level: info] state: read
[Time: 21.06.22 20:03:30] [Level: info] transition: await
[Time: 21.06.22 20:03:31] [Level: info] state: await
[CTRL] GET /status
127.0.0.1 - - [21/Jun/2022 20:03:32] "GET /api/status HTTP/1.0" 200 126
[CTRL] GET /data
127.0.0.1 - - [21/Jun/2022 20:03:32] "GET /api/data HTTP/1.0" 200 26
[CTRL] POST /data
127.0.0.1 - - [21/Jun/2022 20:03:33] "POST /api/data?client=a1412abbd77cf888 HTTP/1.0" 200 0
[Time: 21.06.22 20:03:33] [Level: info] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 169, in guarded_run
    self.run()
  File "/usr/local/lib/python3.8/site-packages/FeatureCloud/app/engine/app.py", line 184, in run
    transition = self.current_state.run()
  File "/app/states.py", line 88, in run
    model_params = logistic_regression(c.get_dataframe())
  File "/app/logistic_regression.py", line 7, in logistic_regression
    X, y = np.arange(10).reshape((5, 2))
ValueError: too many values to unpack (expected 2)

[CTRL] GET /status
127.0.0.1 - - [21/Jun/2022 20:03:35] "GET /api/status HTTP/1.0" 200 134
